# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - MEG-1-DevTest

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm i -g @forge/cli
      forge settings set usage-analytics true
      forge lint
    displayName: "npm & forge install"

  - script: |
      forge deploy
    displayName: "running forge deploy"

  - script: |
      forge install --upgrade
    displayName: "upgrading development env"
